name: CI

on:
  push:
    branches: ['**']
    tags: ['v*']
  pull_request:
    branches: ['**']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: actions/checkout@v4
        run: npm run build
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Tests        
        run: npm test
