name: CI

on:
  push:
    branches: ['**']
    tags: ['v*']
  pull_request:
    branches: ['**']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Node Js
        uses: actions/setup-node@v4
        with: 
          node-version: 18
          cache: npm

      - name: Build
        run: npm run build
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set Up Node Js
        uses: actions/setup-node@v4
        with: 
          node-version: 18
          cache: npm

      - name: Tests
        run: npm run test
